import {
  DraftReTweet,
  DraftReplyTweet,
  DraftTweet,
  DraftUser,
} from "./src/Drafts";
import { Tweet, User } from "./src/Model";
import { TwitterSystem } from "./src/TwitterSystem";

const contents = [
  "I like Atlanta.",
  "I'm going to the concert.",
  "You’ll get used to it.",
  "I work for a bank.",
  "We closed the deal successfully.",
  "The big building was blazing with lights.",
  "The sea sparkled in the sunlight.",
  "I have fewer brothers than you.",
  "I have a first name and a surname.",
  "It felt great to disconnect with technology.",
  "They have a big lunch and a small dinner.",
  "My friends are getting dinner tonight,.",
  "The caffeine was making her jittery.",
  "You go on a holiday every summer.",
  "It was a massive lightning storm.",
  "I want someone who is going to inspire me.",
  "Who told you that?",
  "Please, take pity on me!",
  "Tom has always had a big crush on you.",
  "That’s right, and don't you ever forget it!",
  "Yes, you can have a carry on.",
  "After he arrives, we’ll all come out.",
  "I'm not a fan of writing letters.",
  "You should never lie.",
  "The blacksmith makes old-fashioned swords.",
  "She doesn’t teach chemistry.",
  "Odds are that he is cheating on her.",
  "We went to Paris this afternoon.",
  "We generally sing songs all together.",
  "Her grandmother gave her the bracelet.",
  "His boss might get angry with him.",
  "All work and no play makes Jack a dull boy.",
  "They go to a gallery every Saturday.",
  "You guys like meat.",
  "There used to be big trees around my house.",
  "My sister works at the theater.",
  "Let's never speak of this again!",
  "Why me?",
  "Did you say the plant turned purple?",
  "Go home, weirdo!",
  "Property is government.",
  "I can see you.",
  "I’ll get around to it.",
  "That's a pretty big fish you've just caught.",
  "I have a brochure for our vacation.",
  "Soccer is the devil's sport.",
  "He went fast downhill on his sled.",
  "I'd like us to repair our differences.",
  "I could help mom around here.",
  "This shouldn't be a big deal.",
  "You can either stay or leave.",
  "He was wearing a vest.",
  "They rode their bikes to the beach.",
  "That will do.",
  "He has a nice restaurant near the lake.",
  "We liked the movie.",
  "The other baristas are so weird.",
  "It's a big deal to Tom, I think.",
  "Are trees green or blue?",
  "Where are you going?",
  "It doesn’t rain here in the summer.",
  "The tables were made of fake wood.",
  "I'm not as big a fool as you think I am.",
  "Don't forget to wash behind your knees.",
  "I have a birthday coupon to use.",
  "I ordered a new laptop case yesterday.",
  "I'm against big government.",
  "She has a beehive full of bees.",
  "It gives you more.",
  "Oil is smelly.",
  "she disrespected my mother.",
  "When I am hungry, I eat food.",
  "The black lipstick was very chalky.",
  "That was the president on the phone.",
  "Tigers are gorgeous.",
  "She hopes to get a job.",
  "Tokyo is bigger than Rome.",
  "Big men are not necessarily strong men.",
  "Cry all you want!",
  "What am I supposed to do now?",
  "You have no idea what a relief it is.",
  "He bonded with his father over music.",
  "There is a big stack of mail on the table.",
  "Always stop when you see the sign.",
  "I've got too much work to do.",
  "The police violently defend it.",
  "I am so thankful for this opportunity.",
  "Those pants are too tight.",
  "She’s trying to drown her sorrows.",
  "She always forgets her purse.",
  "I just walked on the lamest window.",
  "I'm asking as a friend.",
  "The businessman had many important meetings.",
  "I’ve got to go now.",
  "It's so expensive I want to die.",
  "We should be able to resolve our differences.",
  "What did he tell you?",
  "I miss the beach.",
  "You could release half of us.",
  "Does she drink coffee?",
  "I want someone who is going to inspire me.",
  "She forgot to water the plant for two months.",
  "Traveling in a helicopter is scary.",
  "He assured me he would keep his promise.",
  "I forgot my shopping list at home.",
  "The sooner I get to bed the better.",
  "Black attracts sunlight more than white.",
  "Her paintings are works of art.",
  "I'm sick of online dating.",
  "We can make ice cream.",
  "He said he always carried a gun.",
  "This could change all of our lives.",
  "The kids were smiling from ear to ear.",
  "He opened the door.",
  "She attended kindergarten in 2013.",
  "Technology makes us forget our past.",
  "Have a cigarette, won’t you?",
  "We've got a major job ahead of us.",
  "Could you tell me the way to the station?",
  "Are you all right?",
  "Oysters are slimy.",
  "His liver was failing.",
  "I see more than one star.",
  "It's stressful to watch other people sing.",
  "Soccer is the devil's sport.",
  "This song is very special to me.",
  "My mother never lies.",
  "The books will be difficult to find in Japan.",
  "I'd like to check your blood pressure.",
  "It's the biggest sports shop in the region.",
  "Your house is beautiful.",
  "Tom is taller than you are.",
  "Water freezes at a very cold temperature.",
  "She bought a book at Powell's.",
  "She usually has to give in to her big sister.",
  "It won’t happen in our lifetime.",
  "Shape up or ship out!",
  "Are you cold?",
  "Tom is just a farm boy living in a big city.",
  "Mr. White went to the store last night.",
  "We often call him by his nickname.",
  "You, as the maker, get to decide the design.",
  "A skirt can be fancier than jeans.",
  "Naps make me feel lazy.",
  "I want to ask them when their big day is.",
  "He made his way through the forest.",
  "“Jimmy,” my grandmother warns.",
  "Well, that's a big surprise.",
  "She went to sleep after 12.",
  "Nobody is out there trying to be happy.",
  "I am afraid of dark afternoons.",
  "He has made a big improvement in tennis.",
  "I'm against big government.",
  "A wet road is usually slippery.",
  "It's easier to clean with disposable dishes.",
  "You guys like meat.",
  "What a big dog!",
  "Don't even look at me!",
  "This is just too big for one person to carry.",
  "What do you like to do when you’re alone?",
  "I owe Tom big time.",
  "All the swings are full.",
  "A new movie is better than an old one.",
  "The answering machine was full.",
  "Tigers live at the zoo.",
  "Options are limited.",
  "Bowls can be any color.",
  "The sunset was breathtaking.",
  "She has a beehive full of bees.",
  "I don't know much about banking.",
  "A wet road is usually slippery.",
  "We're coming to get you.",
  "This lasagna is delicious.",
  "He was wearing a vest.",
  "You don't have to pay rent for two years.",
  "I'm going to crash at your place.",
  "Is football a sport?",
  "Being late is okay, but only sometimes.",
  "She froze at the sight of the big spider.",
  "Wiggle your fingers!",
  "Her paintings are works of art.",
  "Another cat showed up at my house.",
  "The train leaves in ten minutes.",
  "I hate being late more than anything.",
  "I like the Wimbledon.",
  "She bought a book at Powell's.",
  "She had a big, radiant smile.",
  "We are buzzing on this espresso.",
  "Lincoln shot them.",
  "You'd better look before you jump.",
  "Peter ate french fries.",
  "I have a bunch of things I need to do.",
  "Anakin Skywalker is a tragic character.",
  "The sun comes up in the east.",
  "Tinder doesn't work.",
  "We weren't in the best place.",
  "He is bigger than all the other boys.",
  "How do you like it?",
  "May I have some water?",
  "Do pigs like milk?",
  "I get on the bus.",
  "I want you to remember that.",
  "She attended kindergarten in 2013.",
  "This should help you remember.",
  "I go back to bedroom.",
  "You can tell that the horse is fast.",
  "Oysters are disgusting.",
  "Allergies made him sneeze a lot.",
  "It's raining outside.",
  "You may choose whatever you like.",
  "“Jimmy,” my grandmother warns.",
  "I just got hired at this restaurant.",
  "This shop is much nicer.",
  "I could cook dinner.",
  "I do not like zoos.",
  "The taxes are included in the price.",
  "What are you looking for?",
  "That's it, go to time-out!",
  "Keep your hands to yourself!",
  "Here is David with his guitar.",
  "I'm on the list.",
  "Last time I went on vacation I rode a horse.",
  "I must have my TV set checked.",
  "It's the size of a golf ball.",
  "Let sleeping dogs lie.",
  "I do not eat meat.",
  "Tokyo is bigger than Rome.",
  "You'd better look before you jump.",
  "he is easily offended.",
  "It's a big country, Tom.",
  "I bet he’ll be late.",
  "I made bacon.",
  "It's so expensive I want to die.",
  "Breaking glass can make a loud noise.",
  "I do have a crush, but it's not mutual.",
  "He showed us how to snap the pencil.",
  "The wall had fresh paint on it.",
  "Does he have a big family?",
  "I take ten minutes to get there.",
  "Time's up!",
  "You're running a big risk in trusting him.",
  "A ship appeared on the horizon.",
  "I hate being late more than anything.",
  "She hopes to get a job.",
  "My cat runs very fast.",
  "It doesn't matter what college you went to.",
  "Tom kept me from making a big mistake.",
  "My parents are from China.",
  "I was born a very grumpy baby.",
  "Most big Japanese firms depend on exports.",
  "Always stop when you see the sign.",
  "In Chicago, in December, it got dark at 4 pm.",
  "The police violently defend it.",
  "Big men are not necessarily strong men.",
  "He's finally stopping.",
  "It is clear that he has made a big mistake.",
  "You may choose whatever you like.",
  "Does Amelia know?",
  "That's a mistake, isn't it?",
  "Did you see how big their house is?",
  "There is nothing else I'd rather be doing.",
  "You're taking a risk coming here.",
  "She doesn’t see Peter every day.",
  "I seriously doubt she actually believes you.",
  "My friends are getting dinner tonight,.",
  "Yesterday's board meeting was a big success.",
  "She forgot to water the plant for two months.",
  "This shouldn't be a big deal.",
  "Space grey is a weird color.",
  "I need to go back to school.",
  "The dog barked at the cat.",
  "Sports is one outlet to let off steam.",
  "Bowls can be any color.",
  "I left some donuts on the side of the road.",
  "The train is coming early today.",
  "I have an organic banana bread maker.",
  "Hurry up, slowpoke!",
  "Do you have any suggestions for me?",
  "Please, take pity on me!",
  "What does your room look like?",
  "A lovely day isn't it.",
  "This would be a fun place to get married.",
  "I want to see you.",
  "He was a horrible dancer.",
  "Ask your guest if you could serve them tea.",
  "Going to a bar is a fun thing to do.",
  "She has a beehive full of bees.",
  "They had a very bad breakup.",
  "I do not want to smoke.",
  "She’s very gifted.",
  "Tom didn't tell us how big your house was.",
  "He is holding his wrist.",
  "The way you said that didn't make sense.",
  "everything is so expensive.",
  "every decision has an antecedent.",
  "My favorite one smells like roses.",
  "Are you cold?",
  "Stand up straight!",
  "Why on earth would you wear a tie like that?",
  "Can you help me?",
  "His looks are always funny.",
  "She plays basketball.",
  "She will switch the light off.",
  "This problem is much bigger than we thought.",
  "I speak English.",
  "He's an agent for a big insurance company.",
  "I just saw the most eccentric brick.",
  "I'm single.",
  "She is my younger sister.",
  "They’re as different as night and day.",
  "Robert tends to talk big.",
  "Bridges are art.",
  "I wanted to read the book.",
  "The jar of candles was ready on the table.",
  "She is my mother.",
  "The train is coming early today.",
  "Don’t open the door!",
  "They have a big lunch and a small dinner.",
  "Am I in the White House?",
  "Why did you come?",
  "Asia has a very long and interesting history.",
  "This is the biggest car in the world.",
  "I have a small house.",
  "I'll see to it.",
  "We go to a gallery every Sunday.",
  "We are going to have the best day.",
  "We are buzzing on this espresso.",
  "He wanted to get the cheese so badly.",
  "I'll make a list and give it to Samantha.",
  "He suddenly appeared in the party.",
  "Your house is beautiful.",
  "The castle is on top of a cliff.",
  "We will make a snowman this winter.",
  "That’s a wrap for me.",
  "We can get ice cream.",
  "She dissed my mother.",
  "What we had was a total lie.",
  "Space grey is a weird color.",
  "I own a lot of property in Chicago.",
  "I could help mom around here.",
  "He is my grandfather.",
  "Sarey lives alone in a remote cabin.",
  "I have a hairless cat.",
  "I won’t phone my friend till Bob arrives.",
  "The company suffered major losses.",
  "He has a short fuse.",
  "I love you more than I've ever loved my dog.",
  "After he arrives, we’ll all come out.",
  "It takes two to tango.",
  "I feel like blowing something up.",
  "It's raining outside.",
  "We have a dinner setup for us.",
  "There was a big gold star on the door.",
  "Apple picking is not in season.",
  "My hat is cooler than Jim's.",
  "This box is three times as big as that one.",
  "Can’t you open the door?",
  "Does Amelia know?",
  "Let's never speak of this again!",
  "I seriously doubt she actually believes you.",
  "New experiences are the best.",
  "I am here to be pushed to a higher level.",
  "The plant was fake but looked very real.",
  "We've got much bigger problems to deal with.",
  "Taking chances can be risky.",
  "I could help dad around here.",
  "She washed the grapes.",
  "She liked to wear a lot of rings.",
  "Options are limited.",
  "The big fire reduced the whole town to ashes.",
  "It's an important company.",
  "Rosa crossed Mary's name off the list.",
  "His boss might get angry with him.",
  "I'll be back.",
  "We drink coffee every morning.",
  "One cannot live on bread alone.",
  "Go home, weirdo!",
  "She has blue eyes.",
  "I am just extremely proud of him.",
  "Which is deeper, a lake or an ocean?",
  "I miss my girlfriend.",
  "We pay it tax in the form of rent and profit.",
  "I love land.",
  "Hairless cats scare me.",
  "There was a big fire in my neighborhood.",
  "The girl was sitting on the ledge.",
  "He ran his horse up the hill.",
  "He adds something different to the team.",
  "That's typically how it goes now.",
  "They live in a beautiful house.",
  "There is a big park near my school.",
  "He's working with theme.",
  "Tom has big plans.",
  "Japanese tourists abroad are big spenders.",
  "I want to know what is going on.",
  "Her expression was unreadable.",
  "Please don't touch that!",
  "How beautiful she is!",
  "What's bothering you?",
  "Keep your hands to yourself!",
  "It only #works when I'm Martinique.",
  "I saw one of these in Sao Tome and Principe and I bought one.",
  "heard about this on original pilipino music #radio, decided to #give it a try.",
  "one of my hobbies is poetry. and when i'm writing poems this #works great.",
  "i use it until further notice when i'm in my station.",
  "i use it every Tuesday when i'm in my pub.",
  "heard about this on gypsy jazz #radio, decided to #give it a try.",
  "My co-worker Namon has one of these. He says it looks funny-looking.",
  "It only #works when I'm Samoa.",
  "It only #works when I'm Kuwait.",
  "My tiger #loves to play with it.",
  "i use it never when i'm in my #nightclub.",
  "heard about this on brazilian #radio, decided to #give it a try.",
  "My #neighbor Lori has one of these. She #works as a taxidermist and she says it looks whopping.",
  "i use it from now on when i'm in my safehouse.",
  "I tried to shatter it #but got potato all over it.",
  "I tried to electrocute it #but got sweetmeat all over it.",
  "I saw one of these in Tanzania and I bought one.",
  "i use it this time when i'm in my port-a-potty.",
  "this #flower is brown.",
  "The #box this comes in is 4 mile by 5 inch and weights 19 megaton!",
  "#talk about surprise!!!",
  "My #neighbor Alida has one of these. She #works as a gambler and she says it looks spotless.",
  "My peacock #loves to play with it.",
  "i use it barely when i'm in my store.",
  "It only #works when I'm Samoa.",
  "i use it for 10 weeks when i'm in my jail.",
  "The #box this comes in is 5 yard by 6 centimeter and weights 18 gram!!",
  "I saw one of these in Nauru and I bought one.",
  "My co-worker Delton has one of these. He says it looks slender.",
  "I saw one of these in Sao Tome and Principe and I bought one.",
  "this #flower is slurpee.",
  "It only #works when I'm Wake Island.",
  "i use it until further notice when i'm in my #nightclub.",
  "My #neighbor Honora has one of these. She #works as a reporter and she says it looks enormous.",
  "this #flower is brown.",
  "This #flower #works considerably well. It mildly improves my basketball by a lot.",
  "This #flower #works quite well. It pointedly improves my golf by a lot.",
  "I saw one of these in Cote d'Ivoire and I bought one.",
  "this #flower is nifty.",
  "My co-worker Houston has one of these. He says it looks invisible.",
  "#talk about contempt!!!",
  "My dog #loves to play with it.",
  "this #flower is complimentary.",
  "I saw one of these in Haiti and I bought one.",
  "I tried to maim it #but got nectarine all over it.",
  "this #flower is snowy.",
  "I saw one of these in Grenada and I bought one.",
  "This #flower #works too well. It nonchalantly improves my baseball by a lot.",
  "This #flower #works extremely well. It wetly improves my tennis by a lot.",
  "#talk about pleasure!",
  "I tried to slay it #but got truffle all over it.",
  "I saw one of these in Grenada and I bought one.",
  "#talk about sadness!",
  "My #neighbor Georgine has one of these. She #works as a fireman and she says it looks colorful.",
  "heard about this on hip-hop music #radio, decided to #give it a try.",
  "I saw one of these in Tanzania and I bought one.",
  "My co-worker Cato has one of these. He says it looks sopping.",
  "this #tree is amiable.",
  "My demon #loves to play with it.",
  "My co-worker Cato has one of these. He says it looks sopping.",
  "heard about this on wonky #radio, decided to #give it a try.",
  "heard about this on bouyon #radio, decided to #give it a try.",
  "heard about this on gypsy jazz #radio, decided to #give it a try.",
  "I tried to pinch it #but got peanut all over it.",
  "I tried to scratch it #but got cheeseburger all over it.",
  "The #box this comes in is 5 light-year by 6 foot and weights 17 megaton!!!",
  "#talk about sadness.",
  "#talk about sadness.",
  "#talk about contentment!!!",
  "My jaguar #loves to play with it.",
  "My co-worker Houston has one of these. He says it looks invisible.",
  "I tried to maim it #but got nectarine all over it.",
  "#talk about bliss!!",
  "My #neighbor Aldona has one of these. She #works as a butler and she says it looks humongous.",
  "#talk about sadness!",
  "this #tree is perplexed.",
  "The #box this comes in is 3 meter by 6 yard and weights 12 pound.",
  "one of my hobbies is drawing. and when i'm drawing this #works great.",
  "#talk about optimism!!!",
  "heard about this on hip-hop music #radio, decided to #give it a try.",
  "It only #works when I'm Niue.",
  "one of my hobbies is scuba diving. and when i'm scuba diving this #works great.",
  "My co-worker Alek has one of these. He says it looks white.",
  "It only #works when I'm Guernsey.",
  "This #tree #works outstandingly well. It beautifully improves my basketball by a lot.",
  "My co-worker Nile has one of these. He says it looks crooked.",
  "It only #works when I'm Chad.",
  "My dog #loves to play with it.",
  "#talk about anticipation!",
  "#talk about lust!!",
  "this #tree is light-hearted.",
  "i use it until further notice when i'm in my station.",
  "this #tree is slurpee.",
  "#talk about hatred.",
  "this #tree is snowy.",
  "My co-worker Reed has one of these. He says it looks microscopic.",
  "My #neighbor Betha has one of these. She #works as a teacher and she says it looks wide.",
  "The #box this comes in is 5 foot by 6 inch and weights 17 pound!!!",
  "It only #works when I'm Cook Islands.",
  "It only #works when I'm Malaysia.",
  "This #birds #works very well. It romantically improves my football by a lot.",
  "I saw one of these in Barbados and I bought one.",
  "one of my hobbies is drawing. and when i'm drawing this #works great.",
  "I saw one of these in Sao Tome and Principe and I bought one.",
  "this #birds is awesome.",
  "This #birds #works quite well. It romantically improves my golf by a lot.",
  "this #birds is snowy.",
  "My #neighbor Georgie has one of these. She #works as a busboy and she says it looks brown.",
  "i use it once in a while when i'm in my ring.",
  "My velociraptor #loves to play with it.",
  "My jaguar #loves to play with it.",
  "My co-worker Rey has one of these. He says it looks uneven.",
  "one of my hobbies is skateboarding. and when i'm skateboarding this #works great.",
  "My co-worker Tyron has one of these. He says it looks stout.",
  "My #neighbor Julisa has one of these. She #works as a bartender and she says it looks crooked.",
  "i use it until further notice when i'm in my #nightclub.",
  "This #birds #works outstandingly well. It grudgingly improves my baseball by a lot.",
  "It only #works when I'm Rwanda.",
  "one of my hobbies is antique-shopping. and when i'm antique-shopping this #works great.",
  "#talk about sadness!!",
  "i use it biweekly when i'm in my greenhouse.",
  "#talk about interest!!",
  "I tried to electrocute it #but got sweetmeat all over it.",
  "My co-worker Cato has one of these. He says it looks sopping.",
  "#talk about irritation.",
  "one of my hobbies is toy collecting. and when i'm collecting toys this #works great.",
  "I saw one of these in New Zealand and I bought one.",
  "My #neighbor Lonnie has one of these. She #works as a hobbit and she says it looks microscopic.",
  "this #birds is complimentary.",
  "i use it barely when i'm in my store.",
  "My co-worker Reed has one of these. He says it looks microscopic.",
  "My tiger #loves to play with it.",
  "i use it once a week when i'm in my firetruck.",
  "I tried to scratch it #but got cheeseburger all over it.",
  "i use it every Tuesday when i'm in my homeless shelter.",
  "this #birds is amiable.",
  "this #birds is amiable.",
  "The #box this comes in is 3 kilometer by 5 inch and weights 13 ton.",
  "The #box this comes in is 4 yard by 5 kilometer and weights 11 pound!",
  "My porcupine #loves to play with it.",
  "#talk about remorse!!!",
  "I saw one of these in Barbados and I bought one.",
  "The #box this comes in is 4 kilometer by 5 mile and weights 17 gram.",
  "My baboon #loves to play with it.",
  "heard about this on dance-rock #radio, decided to #give it a try.",
  "i use it profusely when i'm in my garage.",
  "I saw one of these in Moldova and I bought one.",
  "It only #works when I'm Guernsey.",
  "This #birds #works quite well. It professionally improves my soccer by a lot.",
  "i use it usually when i'm in my alley.",
  "This #peace #works outstandingly well. It beautifully improves my basketball by a lot.",
  "The #box this comes in is 3 centimeter by 5 kilometer and weights 13 ounce!!",
  "My co-worker Ali has one of these. He says it looks towering.",
  "I tried to maul it #but got onion all over it.",
  "#talk about sadness!",
  "My #neighbor Montserrat has one of these. She #works as a circus performer and she says it looks shriveled.",
  "I saw one of these in Canada and I bought one.",
  "My #neighbor Julisa has one of these. She #works as a bartender and she says it looks crooked.",
  "I tried to hang it #but got jelly bean all over it.",
  "#talk about boredom!!!",
  "My #neighbor Alida has one of these. She #works as a gambler and she says it looks spotless.",
  "one of my hobbies is guitar. and when i'm playing guitar this #works great.",
  "This #peace #works quite well. It professionally improves my soccer by a lot.",
  "It only #works when I'm Mauritania.",
  "It only #works when I'm Juan de Nova Island.",
  "I saw one of these in Sao Tome and Principe and I bought one.",
  "i use it daily when i'm in my courthouse.",
  "The #box this comes in is 5 foot by 6 inch and weights 17 pound!!!",
  "i use it centenially when i'm in my greenhouse.",
  "This #peace #works certainly well. It accidentally improves my baseball by a lot.",
  "I saw one of these in Bhutan and I bought one.",
  "This #peace #works certainly well. It excitedly improves my football by a lot.",
  "i use it once a week when i'm in my firetruck.",
  "I saw one of these in Juan de Nova Island and I bought one.",
  "My #neighbor Fannie has one of these. She #works as a teacher and she says it looks spiky.",
  "The #box this comes in is 5 yard by 6 centimeter and weights 12 kilogram.",
  "My co-worker Merwin has one of these. He says it looks bubbly.",
  "The #box this comes in is 3 light-year by 5 meter and weights 10 ounce!",
  "I saw one of these in Finland and I bought one.",
  "It only #works when I'm Malaysia.",
  "this #peace is ghetto.",
  "My #neighbor Georgine has one of these. She #works as a fireman and she says it looks colorful.",
  "this #peace is ghetto.",
  "I tried to scratch it #but got cheeseburger all over it.",
  "I saw one of these in Finland and I bought one.",
  "This #peace #works considerably well. It recklessly improves my basketball by a lot.",
  "i use it every Tuesday when i'm in my store.",
  "i use it for 10 weeks when i'm in my jail.",
  "#talk about optimism!!!",
  "My #neighbor Lonnie has one of these. She #works as a hobbit and she says it looks microscopic.",
  "this #peace is gracious.",
  "I tried to impale it #but got fudge all over it.",
  "#talk about surprise!!!",
  "My tiger #loves to play with it.",
  "My scarab beetle #loves to play with it.",
  "I saw one of these in Moldova and I bought one.",
  "My co-worker Archer has one of these. He says it looks crooked.",
  "The #box this comes in is 4 meter by 5 foot and weights 18 kilogram.",
  "The #box this comes in is 4 mile by 5 inch and weights 19 megaton!",
  "My bass #loves to play with it.",
  "heard about this on bouyon #radio, decided to #give it a try.",
  "My terrier #loves to play with it.",
  "this #earth is nifty.",
  "This #earth #works certainly well. It excitedly improves my football by a lot.",
  "I tried to slay it #but got truffle all over it.",
  "The #box this comes in is 5 kilometer by 6 meter and weights 20 ounce!",
  "one of my hobbies is hiking. and when i'm hiking this #works great.",
  "My porcupine #loves to play with it.",
  "It only #works when I'm Azerbaijan.",
  "i use it every Tuesday when i'm in my homeless shelter.",
  "one of my hobbies is guitar. and when i'm playing guitar this #works great.",
  "this #earth is papery.",
  "I saw one of these in Nauru and I bought one.",
  "heard about this on songo #radio, decided to #give it a try.",
  "The #box this comes in is 5 light-year by 6 foot and weights 17 megaton!!!",
  "It only #works when I'm Cook Islands.",
  "one of my hobbies is skateboarding. and when i'm skateboarding this #works great.",
  "This #earth #works too well. It nonchalantly improves my baseball by a lot.",
  "The #box this comes in is 3 inch by 6 centimeter and weights 15 ounce!",
  "My goldfinch #loves to play with it.",
  "It only #works when I'm Finland.",
  "I saw one of these in Bhutan and I bought one.",
  "This #earth #works very well. It harmonically improves my tennis by a lot.",
  "I saw one of these in Tanzania and I bought one.",
  "My baboon #loves to play with it.",
  "i use it profusely when i'm in my garage.",
  "I tried to annihilate it #but got bonbon all over it.",
  "This #earth #works extremely well. It wetly improves my tennis by a lot.",
  "I tried to decapitate it #but got coconut all over it.",
  "My #neighbor Betha has one of these. She #works as a teacher and she says it looks wide.",
  "The #box this comes in is 5 yard by 6 centimeter and weights 12 kilogram.",
  "It only #works when I'm Kuwait.",
  "this #earth is standard.",
  "The #box this comes in is 4 mile by 5 yard and weights 18 pound!!",
  "It only #works when I'm Malaysia.",
  "one of my hobbies is guitar. and when i'm playing guitar this #works great.",
  "heard about this on melodic death metal #radio, decided to #give it a try.",
  "I saw one of these in Tanzania and I bought one.",
  "i use it never when i'm in my #nightclub.",
  "It only #works when I'm Wake Island.",
  "I tried to slay it #but got truffle all over it.",
  "This #earth #works certainly well. It excitedly improves my football by a lot.",
  "#talk about remorse!!!",
  "My #neighbor Lonnie has one of these. She #works as a hobbit and she says it looks microscopic.",
  "My co-worker Linnie has one of these. He says it looks wide.",
  "#talk about hatred.",
  "The #box this comes in is 3 yard by 6 light-year and weights 15 gram!!!",
  "heard about this on hip-hop music #radio, decided to #give it a try.",
  "It only #works when I'm Cook Islands.",
  "My #neighbor Ardeth has one of these. She #works as a gasman and she says it looks fuzzy.",
  "This #forest #works really well. It sympathetically improves my baseball by a lot.",
  "It only #works when I'm Kuwait.",
  "This #forest #works quite well. It professionally improves my soccer by a lot.",
  "heard about this on chicha #radio, decided to #give it a try.",
  "#talk about pleasure!",
  "i use it for 10 weeks when i'm in my jail.",
  "#talk about optimism!!!",
  "My co-worker Luka has one of these. He says it looks purple.",
  "I saw one of these in French Southern and Antarctic Lands and I bought one.",
  "I saw one of these in Libya and I bought one.",
  "It only #works when I'm Kuwait.",
  "My ant #loves to play with it.",
  "This #forest #works very well. It harmonically improves my tennis by a lot.",
  "My co-worker Mohamed has one of these. He says it looks brown.",
  "this #forest is whole-grain.",
  "It only #works when I'm Guernsey.",
  "I tried to shatter it #but got potato all over it.",
  "The #box this comes in is 3 light-year by 5 meter and weights 10 ounce!",
  "My co-worker Matthew has one of these. He says it looks gigantic.",
  "I saw one of these in Sao Tome and Principe and I bought one.",
  "I tried to slay it #but got truffle all over it.",
  "#talk about hatred!!!",
  "The #box this comes in is 3 yard by 6 light-year and weights 15 gram!!!",
  "My vulture #loves to play with it.",
  "one of my hobbies is programming. and when i'm programming this #works great.",
  "My scarab beetle #loves to play with it.",
  "this #forest is snowy.",
  "I saw one of these in Sao Tome and Principe and I bought one.",
  "My dog #loves to play with it.",
  "This #forest, does exactly what it's suppose to do.",
  "this #forest is revolting.",
  "I saw one of these in Saint Pierre and Miquelon and I bought one.",
  "My co-worker Linnie has one of these. He says it looks wide.",
  "i use it hardly when i'm in my prison.",
  "This #forest #works considerably well. It secretly improves my basketball by a lot.",
  "i use it this time when i'm in my port-a-potty.",
  "heard about this on brazilian #radio, decided to #give it a try.",
  "i use it once a week when i'm in my firetruck.",
  "My baboon #loves to play with it.",
  "I saw one of these in Haiti and I bought one.",
  "My co-worker Delton has one of these. He says it looks slender.",
  "I tried to nail it #but got strawberry all over it.",
  "This #forest #works excessively well. It mortally improves my golf by a lot.",
  "#talk about surprise!!!",
  "#talk about interest!!",
  "heard about this on bouyon #radio, decided to #give it a try.",
  "This #forest #works considerably well. It mildly improves my basketball by a lot.",
  "#talk about bliss!!",
  "My locust #loves to play with it.",
  "this #mountain is top-notch.",
  "My #neighbor Honora has one of these. She #works as a reporter and she says it looks enormous.",
  "one of my hobbies is mushroom cultivation. and when i'm cultivating mushrooms this #works great.",
  "My co-worker Cato has one of these. He says it looks sopping.",
  "#talk about remorse!!!",
  "My co-worker Fate has one of these. He says it looks tall.",
  "My ant #loves to play with it.",
  "It only #works when I'm Norway.",
  "i use it biweekly when i'm in my greenhouse.",
  "My peacock #loves to play with it.",
  "I tried to decapitate it #but got coconut all over it.",
  "It only #works when I'm Norway.",
  "My #neighbor Lori has one of these. She #works as a taxidermist and she says it looks whopping.",
  "I tried to nab it #but got biscuit all over it.",
  "This #mountain #works quite well. It romantically improves my golf by a lot.",
  "heard about this on timba #radio, decided to #give it a try.",
  "My #neighbor Isabela has one of these. She #works as a taxidermist and she says it looks monochromatic.",
  "I tried to grab it #but got bonbon all over it.",
  "i use it daily when i'm in my courthouse.",
  "It only #works when I'm Norway.",
  "one of my hobbies is guitar. and when i'm playing guitar this #works great.",
  "This is a really good #mountain.",
  "My co-worker Mohamed has one of these. He says it looks brown.",
  "It only #works when I'm Wake Island.",
  "My chicken #loves to play with it.",
  "I tried to electrocute it #but got sweetmeat all over it.",
  "I tried to pepper it #but got prune all over it.",
  "My #neighbor Isabela has one of these. She #works as a taxidermist and she says it looks monochromatic.",
  "this #mountain is ratty.",
  "one of my hobbies is drawing. and when i'm drawing this #works great.",
  "#talk about contentment!!!",
  "I saw one of these in Juan de Nova Island and I bought one.",
  "I saw one of these in Canada and I bought one.",
  "i use it every Tuesday when i'm in my store.",
  "this #mountain is brown.",
  "My co-worker Merwin has one of these. He says it looks bubbly.",
  "#talk about irritation.",
  "My #neighbor Fannie has one of these. She #works as a teacher and she says it looks spiky.",
  "It only #works when I'm Bahrain.",
  "I saw one of these in French Southern and Antarctic Lands and I bought one.",
  "My #neighbor Elisha has one of these. She #works as a fortune teller and she says it looks floppy.",
  "#talk about bliss!!",
  "The #box this comes in is 5 light-year by 6 foot and weights 17 megaton!!!",
  "I tried to shatter it #but got potato all over it.",
  "My #neighbor Lular has one of these. She #works as a cake decorator and she says it looks ragged.",
  "It only #works when I'm Kuwait.",
  "The #box this comes in is 3 meter by 5 foot and weights 11 kilogram.",
  "I saw one of these in The Gambia and I bought one.",
  "I tried to scratch it #but got cheeseburger all over it.",
  "this #mountain is revolting.",
  "My #neighbor Frona has one of these. She #works as a gambler and she says it looks bearded.",
  "#talk about lust!!",
  "I saw one of these in Spratly Islands and I bought one.",
  "I saw one of these in Macau and I bought one.",
  "This #sunset, does exactly what it's suppose to do.",
  "I tried to vomit it #but got bonbon all over it.",
  "It only #works when I'm Malaysia.",
  "this #sunset is ghetto.",
  "My co-worker Archer has one of these. He says it looks crooked.",
  "This #sunset #works quite well. It romantically improves my golf by a lot.",
  "This #sunset #works so well. It delightedly improves my football by a lot.",
  "The #box this comes in is 4 mile by 5 inch and weights 19 megaton!",
  "heard about this on hip-hop music #radio, decided to #give it a try.",
  "My #neighbor Victoria has one of these. She #works as a professor and she says it looks menthol.",
  "This #sunset #works certainly well. It accidentally improves my baseball by a lot.",
  "This #sunset #works certainly well. It excitedly improves my football by a lot.",
  "heard about this on timba #radio, decided to #give it a try.",
  "The #box this comes in is 4 yard by 5 kilometer and weights 11 pound!",
  "My #neighbor Betha has one of these. She #works as a teacher and she says it looks wide.",
  "i use it every Tuesday when i'm in my homeless shelter.",
  "This #sunset #works so well. It delightedly improves my football by a lot.",
  "heard about this on songo #radio, decided to #give it a try.",
  "heard about this on brazilian #radio, decided to #give it a try.",
  "this #sunset is revolting.",
  "My co-worker Linnie has one of these. He says it looks wide.",
  "This #sunset #works excessively well. It speedily improves my baseball by a lot.",
  "#works okay.",
  "i use it never when i'm in my #nightclub.",
  "It only #works when I'm Norway.",
  "It only #works when I'm Rwanda.",
  "one of my hobbies is baking. and when i'm baking this #works great.",
  "heard about this on chicha #radio, decided to #give it a try.",
  "i use it for 10 weeks when i'm in my sauna.",
  "i use it this time when i'm in my port-a-potty.",
  "It only #works when I'm Mauritania.",
  "this #sunset is gracious.",
  "I tried to impale it #but got fudge all over it.",
  "#talk about hatred.",
  "This #sunset #works extremely well. It wetly improves my tennis by a lot.",
  "one of my hobbies is cooking. and when i'm cooking this #works great.",
  "The #box this comes in is 3 light-year by 5 meter and weights 10 ounce!",
  "I saw one of these in Nauru and I bought one.",
  "I saw one of these in Saint Lucia and I bought one.",
  "The #box this comes in is 3 yard by 6 yard and weights 19 pound!!!",
  "My gentoo penguin #loves to play with it.",
  "#talk about pleasure.",
  "My #neighbor Georgie has one of these. She #works as a busboy and she says it looks brown.",
  "heard about this on gypsy jazz #radio, decided to #give it a try.",
  "I saw this on TV and wanted to #give it a try.",
  "My #neighbor Karly has one of these. She #works as a gambler and she says it looks tall.",
  "Life isn’t about getting and having, it’s about giving and being.",
  "Whatever the mind of man can conceive and believe, it can achieve.",
  "Strive not to be a success, but rather to be of value.",
  "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.",
  "I attribute my success to this: I never gave or took any excuse.",
  "You miss 100% of the shots you don’t take.",
  "I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Every strike brings me closer to the next home run.",
  "Definiteness of purpose is the starting point of all achievement.",
  "We must balance conspicuous consumption with conscious capitalism.",
  "Life is what happens to you while you’re busy making other plans.",
  "We become what we think about.",
  "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover.",
  "Life is 10% what happens to me and 90% of how I react to it.",
  "The most common way people give up their power is by thinking they don’t have any.",
  "The mind is everything. What you think you become.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "An unexamined life is not worth living.",
  "Eighty percent of success is showing up.",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "Winning isn’t everything, but wanting to win is.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "Every child is an artist.  The problem is how to remain an artist once he grows up.",
  "You can never cross the ocean until you have the courage to lose sight of the shore.",
  "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
  "Either you run the day, or the day runs you.",
  "Whether you think you can or you think you can’t, you’re right.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.",
  "The best revenge is massive success.",
  "People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily.",
  "Life shrinks or expands in proportion to one’s courage.",
  "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams.  Live the life you have imagined.",
  "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.",
  "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.",
  "Certain things catch your eye, but pursue only those that capture the heart.",
  "Believe you can and you’re halfway there.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
  "Teach thy tongue to say, “I do not know,” and thous shalt progress.",
  "Start where you are. Use what you have.  Do what you can.",
  "When I was 5 years old, my mother always told me that happiness was the key to life.  When I went to school, they asked me what I wanted to be when I grew up.  I wrote down ‘happy’.  They told me I didn’t understand the assignment, and I told them they didn’t understand life.",
  "Fall seven times and stand up eight.",
  "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.",
  "Everything has beauty, but not everyone can see.",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
  "When I let go of what I am, I become what I might be.",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
  "Happiness is not something readymade.  It comes from your own actions.",
  "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.",
  "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.",
  "If the wind will not serve, take to the oars.",
  "You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground.",
  "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.",
  "Too many of us are not living our dreams because we are living our fears.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "If you want to lift yourself up, lift up someone else.",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.",
  "Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless.",
  "You take your life in your own hands, and what happens? A terrible thing, no one to blame.",
  "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.",
  "I didn’t fail the test. I just found 100 ways to do it wrong.",
  "In order to succeed, your desire for success should be greater than your fear of failure.",
  "A person who never made a mistake never tried anything new.",
  "The person who says it cannot be done should not interrupt the person who is doing it.",
  "There are no traffic jams along the extra mile.",
  "It is never too late to be what you might have been.",
  "You become what you believe.",
  "I would rather die of passion than of boredom.",
  "A truly rich man is one whose children run into his arms when his hands are empty.",
  "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
  "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at.",
  "Education costs money.  But then so does ignorance.",
  "I have learned over the years that when one’s mind is made up, this diminishes fear.",
  "It does not matter how slowly you go as long as you do not stop.",
  "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.",
  "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
  "You can’t use up creativity.  The more you use, the more you have.",
  "Dream big and dare to fail.",
  "Our lives begin to end the day we become silent about things that matter.",
  "Do what you can, where you are, with what you have.",
  "If you do what you’ve always done, you’ll get what you’ve always gotten.",
  "Dreaming, after all, is a form of planning.",
  "It’s your place in the world; it’s your life. Go on and do all you can with it, and make it the life you want to live.",
  "You may be disappointed if you fail, but you are doomed if you don’t try.",
  "Remember no one can make you feel inferior without your consent.",
  "Life is what we make it, always has been, always will be.",
  "The question isn’t who is going to let me; it’s who is going to stop me.",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  "It’s not the years in your life that count. It’s the life in your years.",
  "Change your thoughts and you change your world.",
  "Either write something worth reading or do something worth writing.",
  "Nothing is impossible, the word itself says, “I’m possible!”",
];

const users = [
  new DraftUser(
    "jania",
    "jania@gmail.com",
    "jania",
    "https://robohash.org/eumutvoluptatem.jpg?size=50x50&set=set1",
    "https://images.pexels.com/photos/2102649/pexels-photo-2102649.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "tiebold",
    "tiebold@gmail.com",
    "tiebold",
    "https://robohash.org/eumquoasperiores.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/3850561/pexels-photo-3850561.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "corella",
    "corella@gmail.com",
    "corella",
    "https://robohash.org/essedebitisneque.jpg?size=50x50&set=set1",
    "https://images.pexels.com/photos/2228579/pexels-photo-2228579.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "curry",
    "curry@gmail.com",
    "curry",
    "https://robohash.org/quidempariaturquaerat.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/2763967/pexels-photo-2763967.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "berny",
    "berny@gmail.com",
    "berny",
    "https://robohash.org/sitquisat.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/3853623/pexels-photo-3853623.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "chip",
    "chip@gmail.com",
    "chip",
    "https://robohash.org/aconsequatureos.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/1586877/pexels-photo-1586877.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "sandie",
    "sandie@gmail.com",
    "sandie",
    "https://robohash.org/praesentiumvoluptatibuscommodi.jpg?size=50x50&set=set1",
    "https://images.pexels.com/photos/4879684/pexels-photo-4879684.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "nye",
    "nye@gmail.com",
    "nye",
    "https://robohash.org/adipisciinillo.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/5108638/pexels-photo-5108638.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "tallia",
    "tallia@gmail.com",
    "tallia",
    "https://robohash.org/nonharumautem.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/5191383/pexels-photo-5191383.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "ashlen",
    "ashlen@gmail.com",
    "ashlen",
    "https://robohash.org/corruptimaximetotam.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/4038804/pexels-photo-4038804.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "woodman",
    "woodman@gmail.com",
    "woodman",
    "https://robohash.org/temporedolorumunde.bmp?size=50x50&set=set1",
    "https://images.pexels.com/photos/4068331/pexels-photo-4068331.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "kacie",
    "kacie@gmail.com",
    "kacie",
    "https://robohash.org/veritatisiurevoluptatem.jpg?size=50x50&set=set1",
    "https://images.pexels.com/photos/3921857/pexels-photo-3921857.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "des",
    "des@gmail.com",
    "des",
    "https://robohash.org/omnispossimusprovident.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/1586154/pexels-photo-1586154.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "adrienne",
    "adrienne@gmail.com",
    "adrienne",
    "https://robohash.org/facilisnobisdignissimos.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/4069664/pexels-photo-4069664.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "rebecka",
    "rebecka@gmail.com",
    "rebecka",
    "https://robohash.org/voluptatedoloremut.bmp?size=50x50&set=set1",
    "https://images.pexels.com/photos/153653/pexels-photo-153653.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "emilia",
    "emilia@gmail.com",
    "emilia",
    "https://robohash.org/aperiaminmolestiae.bmp?size=50x50&set=set1",
    "https://images.pexels.com/photos/2820885/pexels-photo-2820885.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "mallorie",
    "mallorie@gmail.com",
    "mallorie",
    "https://robohash.org/quiquasinihil.jpg?size=50x50&set=set1",
    "https://images.pexels.com/photos/3028448/pexels-photo-3028448.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "octavia",
    "octavia@gmail.com",
    "octavia",
    "https://robohash.org/quidebitisquis.bmp?size=50x50&set=set1",
    "https://images.pexels.com/photos/2950648/pexels-photo-2950648.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "palmer",
    "palmer@gmail.com",
    "palmer",
    "https://robohash.org/nemosequilaudantium.jpg?size=50x50&set=set1",
    "https://images.pexels.com/photos/3193889/pexels-photo-3193889.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "nicko",
    "nicko@gmail.com",
    "nicko",
    "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/3961619/pexels-photo-3961619.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "juan",
    "juan@gmail.com",
    "juan",
    "https://robohash.org/facilisnobisdignissimos.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/4630002/pexels-photo-4630002.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "rodrigo",
    "rodrigo@gmail.com",
    "rodrigo",
    "https://robohash.org/voluptatedoloremut.bmp?size=50x50&set=set1",
    "https://images.pexels.com/photos/17662/pexels-photo.jpg?puto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "jesus",
    "jesus@gmail.com",
    "jesus",
    "https://robohash.org/aperiaminmolestiae.bmp?size=50x50&set=set1",
    "https://images.pexels.com/photos/2239700/pexels-photo-2239700.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "pepe",
    "pepe@gmail.com",
    "pepe",
    "https://robohash.org/quiquasinihil.jpg?size=50x50&set=set1",
    "https://images.pexels.com/photos/3592799/pexels-photo-3592799.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "martin",
    "martin@gmail.com",
    "martin",
    "https://robohash.org/quidebitisquis.bmp?size=50x50&set=set1",
    "https://images.pexels.com/photos/3544430/pexels-photo-3544430.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "ines",
    "ines@gmail.com",
    "ines",
    "https://robohash.org/nemosequilaudantium.jpg?size=50x50&set=set1",
    "https://images.pexels.com/photos/3304344/pexels-photo-3304344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "flor",
    "flor@gmail.com",
    "flor",
    "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/3735532/pexels-photo-3735532.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "a",
    "a@gmail.com",
    "a",
    "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/3099645/pexels-photo-3099645.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "b",
    "b@gmail.com",
    "b",
    "https://robohash.org/corruptimaximetotam.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/3561946/pexels-photo-3561946.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
  new DraftUser(
    "c",
    "c@gmail.com",
    "c",
    "https://robohash.org/quidempariaturquaerat.png?size=50x50&set=set1",
    "https://images.pexels.com/photos/4936469/pexels-photo-4936469.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
  ),
];

const tweetImages = [
  "https://images.pexels.com/photos/2102649/pexels-photo-2102649.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3850561/pexels-photo-3850561.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2228579/pexels-photo-2228579.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2763967/pexels-photo-2763967.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3853623/pexels-photo-3853623.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/1586877/pexels-photo-1586877.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/5108638/pexels-photo-5108638.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4879684/pexels-photo-4879684.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/5191383/pexels-photo-5191383.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4038804/pexels-photo-4038804.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4068331/pexels-photo-4068331.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3921857/pexels-photo-3921857.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/1586154/pexels-photo-1586154.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4069664/pexels-photo-4069664.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/153653/pexels-photo-153653.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2820885/pexels-photo-2820885.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3028448/pexels-photo-3028448.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2950648/pexels-photo-2950648.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3193889/pexels-photo-3193889.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3961619/pexels-photo-3961619.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/17662/pexels-photo.jpg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4630002/pexels-photo-4630002.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2239700/pexels-photo-2239700.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3592799/pexels-photo-3592799.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3544430/pexels-photo-3544430.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3304344/pexels-photo-3304344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3735532/pexels-photo-3735532.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3099645/pexels-photo-3099645.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3561946/pexels-photo-3561946.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4936469/pexels-photo-4936469.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/1769384/pexels-photo-1769384.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4893857/pexels-photo-4893857.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2911205/pexels-photo-2911205.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4516584/pexels-photo-4516584.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2820876/pexels-photo-2820876.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/5026966/pexels-photo-5026966.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/1684149/pexels-photo-1684149.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2108769/pexels-photo-2108769.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2748123/pexels-photo-2748123.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3987393/pexels-photo-3987393.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3321532/pexels-photo-3321532.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3226462/pexels-photo-3226462.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/5074833/pexels-photo-5074833.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4873819/pexels-photo-4873819.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2008426/pexels-photo-2008426.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2996172/pexels-photo-2996172.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/1987343/pexels-photo-1987343.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/2574672/pexels-photo-2574672.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/3715598/pexels-photo-3715598.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  "https://images.pexels.com/photos/4010464/pexels-photo-4010464.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
];

class Random {
  constructor(seed) {
    this.seed = seed;
  }

  // Simple random number generator with seed
  nextInt(min, max) {
    this.seed = (this.seed * 9301 + 49297) % 233280;
    return min + Math.floor((this.seed / 233280) * (max - min));
  }
}

const random = new Random(100);
const initDate = new Date(2023, 0, 1, 10, 0); // January 1, 2023, 10:00 AM

function getRandomList(list, amountOfElements) {
  return Array(amountOfElements)
    .fill(0)
    .map(() => list[random.nextInt(0, list.length)]);
}

function getRandomElement(list) {
  return getRandomList(list, 1)[0];
}

function getRandomDate(date = new Date(initDate)) {
  const range = Array.from({ length: 25 }, (_, i) => i);
  const hoursToAdd = getRandomElement(range);
  const newDate = new Date(date);
  newDate.setHours(newDate.getHours() + hoursToAdd);
  return newDate;
}

function addUsers(twitterSystem) {
  users.forEach((user) => twitterSystem.addNewUser(user));
}

function addTweetsWithImage(twitterSystem) {
  twitterSystem.users.forEach((user) => {
    getRandomList(contents, 10).forEach((content) => {
      twitterSystem.addNewTweet(
        new DraftTweet(
          user.id,
          content,
          getRandomElement(tweetImages),
          getRandomDate()
        )
      );
    });
  });
}

function addTweetsWithoutImage(twitterSystem) {
  twitterSystem.users.forEach((user) => {
    getRandomList(contents, 10).forEach((content) => {
      twitterSystem.addNewTweet(
        new DraftTweet(user.id, content, null, getRandomDate())
      );
    });
  });
}

function addRetweets(twitterSystem) {
  twitterSystem.users.forEach((user) => {
    getRandomList(twitterSystem.tweets, 7)
      .filter((tweet) => tweet.user !== user)
      .forEach((tweet) => {
        twitterSystem.addReTweet(
          new DraftReTweet(
            user.id,
            tweet.id,
            getRandomElement(contents),
            getRandomDate(tweet.date)
          )
        );
      });
  });
}

function addRepliesWithImage(twitterSystem) {
  twitterSystem.users.forEach((user) => {
    getRandomList(twitterSystem.tweets, 5).forEach((tweet) => {
      twitterSystem.replyTweet(
        new DraftReplyTweet(
          user.id,
          tweet.id,
          getRandomElement(contents),
          getRandomElement(tweetImages),
          getRandomDate(tweet.date)
        )
      );
    });
  });
}

function addRepliesWithoutImage(twitterSystem) {
  twitterSystem.users.forEach((user) => {
    getRandomList(twitterSystem.tweets, 5).forEach((tweet) => {
      twitterSystem.replyTweet(
        new DraftReplyTweet(
          user.id,
          tweet.id,
          getRandomElement(contents),
          null,
          getRandomDate(tweet.date)
        )
      );
    });
  });
}

function addLikes(twitterSystem) {
  twitterSystem.users.forEach((user) => {
    getRandomList(twitterSystem.tweets, 30).forEach((tweet) => {
      twitterSystem.toggleLike(tweet.id, user.id);
    });
  });
}

function addFollowers(twitterSystem) {
  twitterSystem.users.forEach((user) => {
    getRandomList(twitterSystem.users, 4)
      .filter((otherUser) => otherUser !== user)
      .forEach((otherUser) => {
        twitterSystem.toggleFollow(user.id, otherUser.id);
      });
  });
}

export function getTwitterSystem() {
  const twitterSystem = new TwitterSystem();
  addUsers(twitterSystem);
  addTweetsWithImage(twitterSystem);
  addTweetsWithoutImage(twitterSystem);
  addRetweets(twitterSystem);
  addRepliesWithImage(twitterSystem);
  addRepliesWithoutImage(twitterSystem);
  addLikes(twitterSystem);
  addFollowers(twitterSystem);
  return twitterSystem;
}
